name: Automation Demo

# When we push to our default branches, 
# we want to run this workflow.
on: 
   push:
    branches:
      - main
   workflow_dispatch:
     inputs:
       pokemon:
         description: 'Pokemon to add to readme'
         required: false
         default: 'pikachu'

# Define the things to do within the workflow.
jobs:
    # run a job called ourfirstjob
    # on the latest version of Ubuntu.
    ourfirstjob:
        runs-on: ubuntu-latest
        # steps are the things we want to do
        steps:
        - run: echo "Hello, World!"

        - uses: actions/checkout@v4


        - run: | 
                ls -a .
                echo "All files of pwd listed above"


    oursecondjob:
        runs-on: windows-latest
        # steps are the things we want to do
        steps:
        - name: Hello World
          run: echo "Hello, World!"

        - name: Get a copy of the repo files
          uses: actions/checkout@v4
    
        
        - name: run multiple commands
          run: |
            ls .
            echo "All files of pwd listed above"
        - run: |
            dir
            echo "All files of pwd listed above"

    pokemonimagejob: 
        needs: [ourfirstjob, oursecondjob]
        name: Add pokemon image to readme
        runs-on: ubuntu-latest
        steps:
        - uses: ibrahiem96/poke-readme-action@main
          with:
            pokemon: ${{ inputs.pokemon || 'pikachu'}}